library("SnowballC")
library("wordcloud")
library("tm")
library("RColorBrewer")
file=readLines(file.choose())
docs<-VCorpus(VectorSource(file))
toSpace <- content_transformer(function(x,pattern)gsub(pattern," ",x))
docs1<-tm_map(docs,toSpace,"/")
docs1<-tm_map(docs,toSpace,"@")
docs1<-tm_map(docs,toSpace,"#")
strwrap(docs1)
docs1<-tm_map(docs,content_transformer(tolower))
docs1<-tm_map(docs,removeNumbers)
docs1<-tm_map(docs,stripWhitespace)
dtm<-TermDocumentMatrix(docs1)
m<-as.matrix(dtm)
v<-sort(rowSums(m),decreasing = TRUE)
d<-data.frame(word=names(v),freq=v)
head(d,10)
wordcloud(words=d$word,freq = d$freq,min.freq=1,max.words=200,random.order=FALSE,rot.per=0.35,colors=brewer.pal(8,"Dark2"))
barplot(d[1:10,]$freq,las=2,names.arg=d[1:10,]$word,col="orange",main="Most Frequent Words",ylab="Word Frequences",xlab="Terms")

